app_default:
    resource: "@AppBundle/Resources/config/routing/default.yml"
    prefix: "/"

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: "/user"

app_animal:
    resource: "@AppBundle/Resources/config/routing/animal.yml"
    prefix: "/animal"