BackendBundle\Entity\Intereses:
    type: entity
    table: intereses
    uniqueConstraints:
        UNIQ_9B6D26FAA76ED395:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tipo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
                default: 'NULL'
        raza:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
                default: 'NULL'
        edad:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: 'NULL'
        provincia:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
                default: 'NULL'
        localidad:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
                default: 'NULL'
        tamanio:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: 'NULL'
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
